### ISSUE TITLE
Cannot connect to local SCGI server

### ISSUE THREAD

**Issue by Parent5446** [skangas/mentor#4] opened 2016-04-29 17:10 UTC
I am not sure if this is a compatibility issue, but trying to run mentor just gives the error message "Unable to connect to scgi://127.0.0.1:5000". rtorrent is running on that port, and I confirmed it using other command-line tools.

**Comment by skangas** [comment] 2016-12-11 07:33
I saw the same symptoms, but they seem to go away when we connect to scgi://127.0.0.1:5000 rather than scgi://localhost:5000. I don't know what the root cause for this is yet, so further investigation is needed. Can you verify if this change fixes the problems on your end?

PS. A side benefit of this is that I added a new script test-rtorrent.py to the repository that will simplify future development and testing.

**Comment by Parent5446** [comment] 2016-12-12 05:29
Things might have changed, but at the time when I tested it, both localhost and 127.0.0.1 had the same issues. At this point, I ended up switching to Deluge anyway because it was more convenient to daemonize than rtorrent. Feel free to close this if you can't reproduce it.

**Comment by skangas** [comment] 2016-12-15 09:14
Thanks! I will close this for now, since I cannot reproduce it.

You may be interested to know that I've added support for using a file based socket (now the default) and in the coming week or so I will release a new version which automatically runs rtorrent in the background. If you're still interested maybe you could take that for a spin when it's released.

Thanks for mentioning Deluge. Maybe in the future, it would be useful adding support for different backends than rtorrent to mentor.

Let me know if you have any other feedback!

**Closed by skangas** 2016-12-15 09:14 UTC

**Comment by skangas** [comment] 2016-12-20 05:41
Related Emacs bug:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-05/msg01099.html
